### ISSUE TITLE
"secrets" folder missing 

### ISSUE THREAD

**Issue by avnc** [malcolmosh/dispatchPi#1]
The tutorial references the file "flask_key.json" in the secrets folder but this is not present in the project.

**Comment by malcolmosh** [comment]
You are meant to generate the contents of the secrets folder yourself. The details are all in this page of the tutorial : https://malcolmosh.github.io/pages/DispatchPi/dispatchpi_part1/

- `client_secret.json` can be downloaded from Google Cloud Platform once you've set up auth
-  `flask_key.json` can be created programatically (it's just a way to create a unique id for your app)
-  `token.json` will be created automatically when you first use your app's authentication flow. 

Let me know if you have any other questions!
