### ISSUE TITLE
Beginner Question

### ISSUE THREAD

**Issue by jonathaneshaw** [malcolmosh/dispatchPi#3]
I'm having a go at trying to build your brilliant photo frame. Thank you for sharing.

 I'm a complete novice.  I'm bit confused as I was expecting to find a secrets sub folder within the server folder containing a flask_key.json file.  But there does not seem to be a secrets folder.

"In the secrets folder, open the flask_key.json file. This is a custom key used to identify your flask app. It’s not strictly needed, but it’s good practice to include one. Replace the empty string with a random string with the code below:..."
https://malcolmosh.github.io/pages/DispatchPi/dispatchpi_part1/

**Comment by malcolmosh** [comment]
Hi ! Thanks for trying the tutorial! You can generate the secrets folder and its contents yourself. I should probably update the tutorial to better explain that. 

Nevertheless I've gone ahead and added an example of the flask_key.json file in the repo. You can change the key in the file, but it's really an inconsequential bit of the tutorial, more to do with how flask works than anything else, IMHO. Good luck with the next steps!
